//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertRequest()
        {
            this.GestionnaireReports = new HashSet<GestionnaireReport>();
        }
    
        public int case_id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string alert_frequence { get; set; }
        public string alert_frequence_periodicity { get; set; }
        public string action_frequence { get; set; }
        public string alert_action_periodicity { get; set; }
        public Nullable<bool> status { get; set; }
        public int executed_by { get; set; }
        public string decisions { get; set; }
        public int decision_id { get; set; }
        public Nullable<System.DateTime> due_date_action { get; set; }
        public Nullable<System.DateTime> end_date_action { get; set; }
        public string application_id { get; set; }
        public Nullable<System.DateTime> triggered_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionnaireReport> GestionnaireReports { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
