//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlertRequest()
        {
            this.GestionnaireReports = new HashSet<GestionnaireReport>();
        }
    
        public int case_id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string alert_frequence { get; set; }
        public string alert_frequence_periodicity { get; set; }
        public string action_frequence { get; set; }
        public string alert_action_periodicity { get; set; }
        public Nullable<bool> status { get; set; }
        public int executed_by { get; set; }
        public string decisions { get; set; }
        public int decision_id { get; set; }
        public Nullable<System.DateTime> due_date_action { get; set; }
        public Nullable<System.DateTime> end_date_action { get; set; }
        public string application_id { get; set; }
        public Nullable<System.DateTime> triggered_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> next_alert_date { get; set; }
        public Nullable<int> nb_occurence { get; set; }
        public Nullable<System.DateTime> next_action_date { get; set; }
        public Nullable<int> nb_occurence_action { get; set; }
        public Nullable<int> occurence_action_duree { get; set; }
        public Nullable<int> occurence_alert_duree { get; set; }
    
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestionnaireReport> GestionnaireReports { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
