//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int doc_id { get; set; }
        public string doc_path { get; set; }
        public string doc_description { get; set; }
        public string doc_comment { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public int uploaded_by { get; set; }
        public int report_id { get; set; }
    
        public virtual GestionnaireReport GestionnaireReport { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
