//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int doc_id { get; set; }
        public string doc_path { get; set; }
        public string doc_description { get; set; }
        public string doc_comment { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public int uploaded_by { get; set; }
        public int report_id { get; set; }
    
        public virtual GestionnaireReport GestionnaireReport { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
