//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionnaireReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionnaireReport()
        {
            this.Documents = new HashSet<Document>();
        }
    
        public int report_id { get; set; }
        public string report_file_path { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<int> userId { get; set; }
        public string comment { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> case_id { get; set; }
        public string report_description { get; set; }
    
        public virtual AlertRequest AlertRequestNew { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
