//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApproved
    {
        public string NUMERO_DOSSIER { get; set; }
        public string CODE_CLIENT { get; set; }
        public string CODE_AGENCE { get; set; }
        public string NUMERO_COMPTE { get; set; }
        public string CLE_COMPTE { get; set; }
        public string INTITULE_COMPTE { get; set; }
        public string SECTEUR_ACTIVITE { get; set; }
        public string TYPE_ENGAGEMENT { get; set; }
        public string MOTIF { get; set; }
        public Nullable<System.DateTime> DATE_MISE_EN_PLACE { get; set; }
        public Nullable<System.DateTime> DATE_1ERE_ECHEANCE { get; set; }
        public Nullable<System.DateTime> DATE_FIN_ECHEANCE { get; set; }
        public Nullable<double> MONTANT_PRET { get; set; }
        public Nullable<double> MONTANT_DEBLOQUE { get; set; }
        public Nullable<double> TAUX_INTERET { get; set; }
        public Nullable<double> TEG { get; set; }
        public Nullable<double> COMMISSION { get; set; }
        public Nullable<double> TAXE { get; set; }
        public Nullable<double> ENCOURS_CREDIT { get; set; }
        public Nullable<double> IMPAYES_CREDIT { get; set; }
        public string PERIODICITE { get; set; }
        public Nullable<double> NBRE_ECHEANCE { get; set; }
        public Nullable<double> DUREE_DE_CREDIT { get; set; }
        public string DOSSIERCREDIT_ETAT { get; set; }
        public string GESTIONNAIRE { get; set; }
        public string EMAIL_CLIENT { get; set; }
        public string GESTIONNAIRE_EMAIL { get; set; }
    }
}
