//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingJob.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanApplication()
        {
            this.AlertRequestNews = new HashSet<AlertRequest>();
        }
    
        public string application_id { get; set; }
        public string loan_name { get; set; }
        public string loan_description { get; set; }
        public string loan_type_desc { get; set; }
        public string mode_payment { get; set; }
        public string loan_amount { get; set; }
        public Nullable<System.DateTime> loan_date { get; set; }
        public string purpose { get; set; }
        public Nullable<bool> loan_status { get; set; }
        public string remarks { get; set; }
        public string processed_by { get; set; }
        public Nullable<int> customer_no { get; set; }
        public string customer_fullname { get; set; }
        public Nullable<System.DateTime> loan_period { get; set; }
        public string loan_rate { get; set; }
        public Nullable<int> financing_code { get; set; }
        public string CODE_AGENCE { get; set; }
        public string NUMERO_COMPTE { get; set; }
        public string CLE_COMPTE { get; set; }
        public string INTITULE_COMPTE { get; set; }
        public string SECTEUR_ACTIVITE { get; set; }
        public string TYPE_ENGAGEMENT { get; set; }
        public Nullable<System.DateTime> DATE_MISE_EN_PLACE { get; set; }
        public Nullable<System.DateTime> DATE_1ERE_ECHEANCE { get; set; }
        public Nullable<System.DateTime> DATE_FIN_ECHEANCE { get; set; }
        public string MONTANT_DEBLOQUE { get; set; }
        public string ENCOURS_CREDIT { get; set; }
        public string IMPAYES_CREDIT { get; set; }
        public string PERIODICITE { get; set; }
        public Nullable<double> NBRE_ECHEANCE { get; set; }
        public string GESTIONNAIRE { get; set; }
        public string EMAIL_CLIENT { get; set; }
        public string GESTIONNAIRE_EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertRequest> AlertRequestNews { get; set; }
        public virtual Type Type { get; set; }
    }
}
